apiVersion: skaffold/v1beta1
kind: Config
build:
    local:
        push: false
    artifacts:
        - image: multi-client
          context: client
          docker:
              dockerfile: Dockerfile.dev
          sync: 
              '**/*.js': .
              '**/*.css': .
              '**/*.html': .
        - image: multi-server
          context: server
          docker:
              dockerfile: Dockerfile.dev
          sync: 
              '**/*.js': .
        - image: multi-server
          context: server
          docker:
              dockerfile: Dockerfile.dev
          sync: 
              '**/*.js': .
deploy:
    kubectl:
            manifests:
                - k8s/client-deployment.yaml
                - k8s/server-deployment.yaml
                - k8s/worker-deployment.yaml
                - k8s/client-cluster-ip-service.yaml
                - k8s/server-cluster-ip-service.yaml
                - k8s/worker-cluster-ip-service.yaml